### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by versoul** [rzymek/meteor-app-version#1]
im install plugin and add file AddVersion.version add tag to git commit and push.
i cant see version in my template, help me please =(

**Comment by rzymek** [comment]
I'll look into it next week

**Comment by rzymek** [comment]
Did you tag your repo using `git tag [tag-name]`?
**Edit**: Just read that you did.
What's the output of `git describe --tags`? Where did you place `AppVersion.version` file?

**Comment by rzymek** [comment]
I do confirm, that it stopped working. Investigation in progress...

**Comment by rzymek** [comment]
The was an issue with async `exec` call. Fix it. Upgrade to 0.0.3
